### ISSUE TITLE
Lack of Styling/Interface for Application

### ISSUE THREAD

**Issue by James-Southgate** [BUAdvDev2023/production-tracking#1]
The current application lacks any styling or user interface, which significantly affects user experience and usability. Without a proper UI, users may find it challenging to navigate and utilize the application effectively. This could lead to decreased user engagement and satisfaction. Implementing a well-designed interface is crucial for improving user interaction, making the application more intuitive, and ensuring a professional appearance. Prioritising UI development will enhance the overall functionality and appeal of the application, ultimately leading to better user adoption and feedback. I am availably to get started on created this interface for your application on Monday if that suits you?

**Comment by Treamas** [comment]
I have improved the styling using CSS and positioned the widgets on the webpage better to improve how the forms look. If you would like to have a crack at improving the UI feel free to create a branch of the main repository.
